language: julia

os:
  - linux
  - osx

julia:
  - 0.7
  - 1.0
  - 1.1
  - 1.2
  - nightly

matrix:
  allow_failures:
    - julia: nightly

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # tags

notifications:
  email: false
